export const collections = [
  { id: 'quranic-verses', name: 'Quranic Verses', arabic: 'الآيات القرآنية' },
  { id: '99-names', name: '99 Names of Allah', arabic: 'الأسماء الحسنى' },
  { id: 'bridal-gift', name: 'Bridal & Gift', arabic: 'مجموعة العروس' },
  { id: 'limited-editions', name: 'Limited Editions', arabic: 'قطع فريدة' },
];

/* Canvas size categories for pricing:
   Large:  30–50″  → $200–$400
   Medium: 10–30″  → $30–$100
   Small:  < 10″   → $5–$20
   Asmaul Husna:    avg $400 (+$100 custom)
   Ayatul Kursi:    avg $350 (+$50 custom)
   Other pieces:    medium +$50 custom, small +$10 custom
*/

export const products = [
  {
    id: 'ayat-al-kursi-teal',
    slug: 'ayat-al-kursi-teal',
    name: 'Ayat al-Kursi — Teal',
    arabicName: 'آية الكرسي',
    collection: 'quranic-verses',
    collectionLabel: 'Ayatul Kursi Collection',
    script: 'Thuluth',
    dimensions: '60 × 30″',
    canvasSize: 'large',
    price: 350,
    customizationFee: 50,
    processingTime: '2–3 weeks',
    description: 'The Verse of the Throne rendered in luminous gold Thuluth script against a hand-marbled teal canvas. Surrounded by a hand-painted floral arabesque border with gold leaf accents. A centerpiece piece for any home.',
    calligrapher: 'Master Hasan, Istanbul',
    image: '/product-ayatul-kursi-teal-1.jpg',
    images: ['/product-ayatul-kursi-teal-1.jpg', '/product-ayatul-kursi-teal-2.jpg'],
    features: ['Hand-gilded gold leaf', 'Archival-grade canvas', 'Floral arabesque border', 'Signed by calligrapher'],
    customizations: ['Color palette', 'Design style', 'Layout inspiration'],
  },
  {
    id: '99-names-burgundy',
    slug: '99-names-burgundy',
    name: '99 Names — Burgundy Diamond',
    arabicName: 'أسماء الله الحسنى',
    collection: '99-names',
    collectionLabel: 'Asmaul Husna Collection',
    script: 'Thuluth',
    dimensions: '60 × 36″',
    canvasSize: 'large',
    price: 400,
    customizationFee: 100,
    processingTime: '~1 month',
    description: 'All 99 beautiful names of Allah arranged in hand-painted diamond medallions across a rich burgundy canvas. Each name is individually composed in gold leaf Thuluth script within jewel-toned panels of blue, green, copper and cream, flanked by intricate floral arabesques.',
    calligrapher: 'Ustad Tariq, Cairo',
    image: '/product-99-names-burgundy-1.jpg',
    images: ['/product-99-names-burgundy-1.jpg', '/product-99-names-burgundy-2.jpg', '/product-99-names-burgundy-3.jpg'],
    features: ['99 individually painted name panels', 'Jewel-toned diamond layout', 'Gold leaf accents throughout', 'Floral arabesque side panels'],
    customizations: ['Color palette', 'Design inspiration', 'Overall aesthetic/style'],
  },
  {
    id: '99-names-black',
    slug: '99-names-black',
    name: '99 Names — Noir Hexagonal',
    arabicName: 'أسماء الله الحسنى',
    collection: '99-names',
    collectionLabel: 'Asmaul Husna Collection',
    script: 'Thuluth',
    dimensions: '48 × 36″',
    canvasSize: 'large',
    price: 400,
    customizationFee: 100,
    processingTime: '~1 month',
    description: 'The 99 names arranged in stunning silver and grey hexagonal cells against a deep black canvas, flanked by geometric star panels in gold. A modern interpretation of a timeless devotion.',
    calligrapher: 'Master Ali, Lahore',
    image: '/product-99-names-black-1.jpg',
    images: ['/product-99-names-black-1.jpg', '/product-99-names-black-2.jpg'],
    features: ['Hexagonal tessellation layout', 'Silver & grey gradient cells', 'Gold geometric star side panels', 'Contemporary noir palette'],
    customizations: ['Color palette', 'Design inspiration', 'Overall aesthetic/style'],
  },
  {
    id: '99-names-green',
    slug: '99-names-green',
    name: '99 Names — Emerald Garden',
    arabicName: 'أسماء الله الحسنى',
    collection: '99-names',
    collectionLabel: 'Asmaul Husna Collection',
    script: 'Thuluth',
    dimensions: '48 × 40″',
    canvasSize: 'large',
    price: 400,
    customizationFee: 100,
    processingTime: '~1 month',
    description: 'The 99 names displayed in interlocking arabesque quatrefoils across a lush emerald green canvas. Vivid greens, teals and burgundy panels are outlined in raised gold, creating a jewel-box effect.',
    calligrapher: 'Ustad Tariq, Cairo',
    image: '/product-99-names-green-2.jpg',
    images: ['/product-99-names-green-1.jpg', '/product-99-names-green-2.jpg', '/product-99-names-green-3.jpg'],
    features: ['Arabesque quatrefoil pattern', 'Raised gold outlining', 'Emerald & teal palette', 'Gold finial accent'],
    customizations: ['Color palette', 'Design inspiration', 'Overall aesthetic/style'],
  },
  {
    id: '99-names-pink',
    slug: '99-names-pink',
    name: '99 Names — Rose Gold',
    arabicName: 'أسماء الله الحسنى',
    collection: '99-names',
    collectionLabel: 'Asmaul Husna Collection',
    script: 'Naskh',
    dimensions: '36 × 36″',
    canvasSize: 'large',
    price: 400,
    customizationFee: 100,
    processingTime: '~1 month',
    description: 'A softer palette for the 99 names — rose, blush and teal panels set against a warm cream canvas. Perfect for contemporary interiors and a beautiful bridal gift.',
    calligrapher: 'Master Hasan, Istanbul',
    image: '/product-99-names-pink-1.jpg',
    images: ['/product-99-names-pink-1.jpg', '/product-99-names-pink-2.jpg'],
    features: ['Soft rose & blush palette', 'Warm cream base canvas', 'Contemporary Naskh script', 'Ideal as a bridal gift'],
    customizations: ['Color palette', 'Design inspiration', 'Overall aesthetic/style'],
  },
  {
    id: 'ayat-al-kursi-sage',
    slug: 'ayat-al-kursi-sage',
    name: 'Ayat al-Kursi — Sage',
    arabicName: 'آية الكرسي',
    collection: 'quranic-verses',
    collectionLabel: 'Ayatul Kursi Collection',
    script: 'Diwani',
    dimensions: '48 × 24″',
    canvasSize: 'large',
    price: 350,
    customizationFee: 50,
    processingTime: '2–3 weeks',
    description: 'The Verse of the Throne in flowing Diwani script on a muted sage-green canvas. Surrounded by delicate gold vine arabesques, creating a piece that feels both classical and contemporary.',
    calligrapher: 'Master Ali, Lahore',
    image: '/product-ayatul-kursi-sage-1.jpg',
    images: ['/product-ayatul-kursi-sage-1.jpg', '/product-ayatul-kursi-sage-2.jpg'],
    features: ['Flowing Diwani calligraphy', 'Hand-painted vine arabesques', 'Sage-green tonal canvas', 'Gold leaf accents'],
    customizations: ['Color palette', 'Design style', 'Layout inspiration'],
  },
  {
    id: 'ayat-al-kursi-blue',
    slug: 'ayat-al-kursi-blue',
    name: 'Ayat al-Kursi — Celestial Blue',
    arabicName: 'آية الكرسي',
    collection: 'quranic-verses',
    collectionLabel: 'Ayatul Kursi Collection',
    script: 'Thuluth',
    dimensions: '40 × 30″',
    canvasSize: 'large',
    price: 350,
    customizationFee: 50,
    processingTime: '2–3 weeks',
    description: 'A serene blue canvas bearing the Verse of the Throne in delicate gold calligraphy. The celestial blue tones evoke the sky, making this piece perfect for bedrooms and quiet spaces.',
    calligrapher: 'Master Hasan, Istanbul',
    image: '/product-ayatul-kursi-blue-1.jpg',
    images: ['/product-ayatul-kursi-blue-1.jpg'],
    features: ['Celestial blue canvas', 'Gold Thuluth calligraphy', 'Serene & calming aesthetic', 'Archival materials'],
    customizations: ['Color palette', 'Design style', 'Layout inspiration'],
  },
  {
    id: 'allah-green',
    slug: 'allah-green',
    name: 'Allah — Emerald',
    arabicName: 'الله',
    collection: 'quranic-verses',
    collectionLabel: 'Calligraphy Collection',
    script: 'Jali Thuluth',
    dimensions: '20 × 24″',
    canvasSize: 'medium',
    price: 80,
    customizationFee: 50,
    processingTime: '1–2 weeks',
    description: 'The name of Allah in majestic Jali Thuluth script, set against a deep emerald green canvas with gold arabesque vine border. A powerful yet intimate devotional piece.',
    calligrapher: 'Ustad Tariq, Cairo',
    image: '/product-allah-green-1.jpg',
    images: ['/product-allah-green-1.jpg', '/product-allah-green-2.jpg'],
    features: ['Jali Thuluth script', 'Emerald green canvas', 'Gold vine border', 'Compact devotional size'],
    customizations: ['Color palette', 'Design adjustments', 'Aesthetic preferences'],
  },
  {
    id: 'ya-hayyu-blue',
    slug: 'ya-hayyu-blue',
    name: 'Ya Hayyu Ya Qayyum',
    arabicName: 'يا حيّ يا قيّوم',
    collection: 'quranic-verses',
    collectionLabel: 'Calligraphy Collection',
    script: 'Diwani',
    dimensions: '36 × 24″',
    canvasSize: 'large',
    price: 250,
    customizationFee: 50,
    processingTime: '2–3 weeks',
    description: 'O Ever-Living, O Self-Sustaining — an invocation rendered in swirling Diwani script on a deep blue canvas with gold accents. A piece that brings serenity and remembrance.',
    calligrapher: 'Master Ali, Lahore',
    image: '/product-ya-hayyu-blue-1.jpg',
    images: ['/product-ya-hayyu-blue-1.jpg', '/product-ya-hayyu-blue-2.jpg'],
    features: ['Swirling Diwani script', 'Deep blue tonal canvas', 'Gold accent details', 'Signed by calligrapher'],
    customizations: ['Color palette', 'Design adjustments', 'Aesthetic preferences'],
  },
  {
    id: 'bismillah-beige',
    slug: 'bismillah-beige',
    name: 'Bismillah — Floral',
    arabicName: 'بسم الله الرحمن الرحيم',
    collection: 'bridal-gift',
    collectionLabel: 'Calligraphy Collection',
    script: 'Diwani',
    dimensions: '36 × 18″',
    canvasSize: 'large',
    price: 220,
    customizationFee: 50,
    processingTime: '2–3 weeks',
    description: 'Bismillah-ir-Rahman-ir-Rahim in warm Diwani script surrounded by a delicate floral border. The warm beige tones and botanical details make this the perfect housewarming or bridal gift.',
    calligrapher: 'Master Hasan, Istanbul',
    image: '/product-bismillah-beige-1.jpg',
    images: ['/product-bismillah-beige-1.jpg', '/product-bismillah-beige-2.jpg'],
    features: ['Warm Diwani calligraphy', 'Delicate floral border', 'Beige tonal canvas', 'Perfect bridal gift'],
    customizations: ['Color palette', 'Design adjustments', 'Aesthetic preferences'],
  },
  {
    id: 'tawakkul-grey',
    slug: 'tawakkul-grey',
    name: 'Tawakkul — Grey Marble',
    arabicName: 'توكّلت على الله',
    collection: 'bridal-gift',
    collectionLabel: 'Calligraphy Collection',
    script: 'Nastaliq',
    dimensions: '24 × 24″',
    canvasSize: 'medium',
    price: 60,
    customizationFee: 50,
    processingTime: '1–2 weeks',
    description: 'I have placed my trust in Allah — a calming grey-marbled canvas with silver and gold script. Part of our mini-canvas collection, ideal for desks, shelves, and intimate spaces.',
    calligrapher: 'Master Ali, Lahore',
    image: '/product-tawakkul-grey-1.jpg',
    images: ['/product-tawakkul-grey-1.jpg', '/product-tawakkul-grey-2.jpg'],
    features: ['Grey marble effect', 'Silver & gold script', 'Intimate canvas size', 'Ideal for shelves & desks'],
    customizations: ['Color palette', 'Design adjustments', 'Aesthetic preferences'],
  },
  {
    id: '5-names-mini',
    slug: '5-names-mini',
    name: '5 Names — Mini Canvas Set',
    arabicName: 'أسماء الله',
    collection: 'bridal-gift',
    collectionLabel: 'Mini Canvas Collection',
    script: 'Various',
    dimensions: '8 × 10″ each',
    canvasSize: 'small',
    price: 15,
    customizationFee: 10,
    processingTime: '1 week',
    description: 'A curated set of five mini canvases, each bearing one of the beautiful names of Allah. Perfect as individual accents or displayed as a group. An ideal gift for any occasion.',
    calligrapher: 'Master Ali, Lahore',
    image: '/product-5-names-mini-1.jpg',
    images: ['/product-5-names-mini-1.jpg'],
    features: ['Set of 5 mini canvases', 'Various script styles', 'Display individually or grouped', 'Perfect gift set'],
    customizations: ['Color palette', 'Design adjustments'],
  },
  {
    id: 'gold-arabesque',
    slug: 'gold-arabesque',
    name: 'Gold Arabesque — Detail',
    arabicName: 'الزخرفة الذهبية',
    collection: 'limited-editions',
    collectionLabel: 'Limited Edition',
    script: 'Ottoman Tezhip',
    dimensions: 'Various sizes',
    canvasSize: 'medium',
    price: 90,
    customizationFee: 50,
    processingTime: '2–3 weeks',
    description: 'A close study of our hand-painted arabesque florals and gold leaf work. Each vine, petal, and leaf is individually rendered by hand in the Ottoman tezhip tradition.',
    calligrapher: 'Master Hasan, Istanbul',
    image: '/product-gold-arabesque-detail.jpg',
    images: ['/product-gold-arabesque-detail.jpg'],
    features: ['Ottoman tezhip tradition', 'Individual hand-painted florals', '24k gold leaf application', 'Museum-quality detail'],
    customizations: ['Color palette', 'Design adjustments', 'Aesthetic preferences'],
  },
];
